repos:
    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.1
      hooks:
        - id: nbstripout
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.14.7
      hooks:
        - id: ruff-check
          args: [ --fix ] # Automatically fixes linting issues
        - id: ruff-format
    - repo: https://github.com/astral-sh/uv-pre-commit
      # uv version.
      rev: 0.9.14
      hooks:
        - id: uv-lock 
    - repo: https://github.com/hukkin/mdformat
      rev: 1.0.0 # Use the latest stable version
      hooks:
        - id: mdformat
          # Optionally add plugins for extensions like GitHub Flavored Markdown (GFM)
          additional_dependencies:
            - mdformat-gfm

    # - repo: local
    #   hooks:
    #     - id: uv-sync
    #       name: uv-sync
    #       entry: ./pre-commit_commands/uv-sync.sh
    #       language: system
    #       stages: [commit]