services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${config_path}:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: America/New_York 
    healthcheck:
          # test: ping -c 1 www.google.com || exit 1
          test: ping -c 1 127.0.0.1:8123 || exit 1
          interval: 1m
          timeout: 10s
          retries: 3
  music-assistant-server:
    image: ghcr.io/music-assistant/server:latest # <<< Desired release version here (or use beta to get the latest beta version)
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - ${config_path}/music-assistant-server/data:/data/
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=info 
    healthcheck:
          # test: ping -c 1 www.google.com || exit 1
          test: timeout 1 bash -c 'cat < /dev/tcp/127.0.0.1/8095' || exit 1
          interval: 1m
          timeout: 10s
          retries: 3
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    # Required for mDNS and IPv6 to work correctly
    network_mode: host
    security_opt:
      # Needed for Bluetooth via dbus
      - apparmor:unconfined
    healthcheck:
          # test: ping -c 1 www.google.com || exit 1
          test: timeout 1 bash -c 'cat < /dev/tcp/127.0.0.1/8095' || exit 1
          interval: 1m
          timeout: 10s
          retries: 3
    volumes:
      # Create an .env file that sets the USERDIR environment variable (e.g., USERDIR=/home/user)
      - ${config_path}/matter-server/data:/data/
      # Required for Bluetooth via D-Bus (uncomment if using Bluetooth)
      # - /run/dbus:/run/dbus:ro
#   music-assistant-skill:
#     image: ghcr.io/alams154/music-assistant-skill:dev
#     environment:
#       - MA_HOSTNAME=<domain> # Domain name, including subdomain #optional, if only using APL devices
#       - API_USERNAME=/run/secrets/API_USERNAME #optional
#       - API_PASSWORD=/run/secrets/API_PASSWORD #optional
#       - PORT=5000 #optional
#       - DEBUG_PORT=5678 #optional
#       - AWS_DEFAULT_REGION=us-east-1 #optional
#     secrets:
#       - API_USERNAME
#       - API_PASSWORD
#     ports:
#       - 5000:5000 # Must match PORT
#       - 5678:5678 # Must match DEBUG_PORT #optional
#     restart: unless-stopped

# secrets:
#   API_USERNAME:
#     file: ./secrets/api_username.txt
#   API_PASSWORD:
#     file: ./secrets/api_password.txt